### ISSUE TITLE
multiple posting on nourishingdestiny.com

### ISSUE THREAD

**Issue by thoughtlead** [thoughtlead/ThoughtLead#12]
We have been experiencing a wierd phenomena where it takes a long time for a post to load and it shows up 2-4 times with one mouse click. I hit "send" and then it appears 2-4 times in a row on the list. THis happens everyday but only on 30% of the posts. -Lon https://github.com/thoughtlead/ThoughtLead/issues/labels/bug

**Comment by wideopenspaces** [comment]
When I deploy the javascript to block multiple submits this should be corrected. Marking as a dupe
