### ISSUE TITLE
Video uploading on TurnAroundSelling

### ISSUE THREAD

**Issue by thoughtlead** [thoughtlead/ThoughtLead#13]
From Stepp:

I up loaded a video last night. Got the same error message too. Please check that it up loaded and is in good operation. Thanks

**Comment by thoughtlead** [comment]
He's going to be sending me the video that he tried to upload it so I can give you the details soon.

**Comment by wideopenspaces** [comment]
Another issue with the audio codec. Once we know what they use to produce the videos, I can help them export video in a format we can convert for the web.
