### ISSUE TITLE
Site moving slowly

### ISSUE THREAD

**Issue by thoughtlead** [thoughtlead/ThoughtLead#16]
Hi Jake,

Do you have thoughts on why the site takes a very long time to execute a process sometimes? Even simple things like showing the login page after clicking login from the home page... today it took about 40 seconds to load. 

If I speak with Engine Yard about it, are there certain things I should bring up with them or mention?

Thanks,

**Comment by wideopenspaces** [comment]
Reposting from the other issue so it's all in one place:

"I wrote to Engine Yard to see if they had any suggestions and here's what they said:

Hello Steven,

I did some research on this to see if I can find any problems. First, I checked your production.log to see if I could find any slow response times in the log. I did see a few, but nothing that would indicate a sustained issue. I also checked your slice and it is in pretty good shape (load is ok and I did see that you are in to swap). Also, I went to the http://masterscenterfortransformation.com site and clicked on the contact link and it loaded for me right away. I am wondering if you are still seeing this issue. If you are could you do a traceroute to see if maybe it is a network issue from where you are to the site? I am not seeing anything that would indicate that there is an issue. Also, I don't see that you are using New Relic at all. I would recommend that you take a look at New Relic as it would help if there are places in your application that could be improved.

thanks
Mike Riley
Application Support Engineer
Engine Yard"

**Comment by wideopenspaces** [comment]
Reposting so I can close a duplicate issue:

"From Engine Yard,

Your site is experiencing a few swap issues when your indexer is running. You are running a full index quite often and that process takes upwards of 250MB which is causing your slice to swap. When this happens your mongrels are slowing down pretty substantially. I would consider adding more memory to your servers in the long term in addition to lessening your indexing frequency.

Thanks."

**Comment by thoughtlead** [comment]
Tyler Bird, Dec 02 12:02 (PST):
I've added a temporary 256 MB of ram in order to prevent the mongrels from going into swap. I then restarted each mongrel one at a time to ensure both were using real ram, instead of swap.

I'm going to ask sales to generate a quote for the extra 256 MB of ram, so that if you decide you'd like to keep it you'll know how much it would cost.

I've checked both sites and they are responsive. As always, we'll keep an eye on things.

Thank you again for choosing Engine Yard!

Thanks,

Tyler Bird

**Comment by thoughtlead** [comment]
Grant Schofield, Dec 02 09:25 (PST):
Your site is experiencing a few swap issues when your indexer is running. You are running a full index quite often and that process takes upwards of 250MB which is causing your slice to swap. When this happens your mongrels are slowing down pretty substantially. I would consider adding more memory to your servers in the long term in addition to lessening your indexing frequency.

Thanks.

**Comment by wideopenspaces** [comment]
Added 256MB of RAM and switching indexer to run less frequently. Closing until something happens again :)
