### ISSUE TITLE
Course description formatting

### ISSUE THREAD

**Issue by thoughtlead** [thoughtlead/ThoughtLead#17]
Under "edit this course" for the "description" is there ANY way to format this text? I'd like to make it presentable and very easy to read but it all just lumps together. Tried HTML codes but that didn't work. I have to convey some VERY important information here and I'm afraid people wil miss it when it's all lumped together.

(from Lonny)

**Comment by wideopenspaces** [comment]
Yes. Try it out on staging now :)
