### ISSUE TITLE
Very slow site response on click sometimes

### ISSUE THREAD

**Issue by thoughtlead** [thoughtlead/ThoughtLead#18]
I wrote to Engine Yard to see if they had any suggestions and here's what they said:

Hello Steven,

I did some research on this to see if I can find any problems. First, I checked your production.log to see if I could find any slow response times in the log. I did see a few, but nothing that would indicate a sustained issue. I also checked your slice and it is in pretty good shape (load is ok and I did see that you are in to swap). Also, I went to the http://masterscenterfortransformation.com site and clicked on the contact link and it loaded for me right away. I am wondering if you are still seeing this issue. If you are could you do a traceroute to see if maybe it is a network issue from where you are to the site? I am not seeing anything that would indicate that there is an issue. Also, I don't see that you are using New Relic at all. I would recommend that you take a look at New Relic as it would help if there are places in your application that could be improved.

thanks 
Mike Riley 
Application Support Engineer 
Engine Yard

**Comment by wideopenspaces** [comment]
Moved this info to the site moving slowly issue and closing this one.
