### ISSUE TITLE
signup and upgrade process issues

### ISSUE THREAD

**Issue by thoughtlead** [thoughtlead/ThoughtLead#23]
Hi Steve,

We are getting reports via Facebook and email, through friends and other informal networks that people are experiencing a variety of problems with the site.  Several have contacted Diane to say they wanted to sign up but couldn't enter anything into the sign up box (this could be the button issue from yesterday).  One has contacted us to say she signed up for Basic level, paid (i've seen the invoice generated) and now when she tries to log in, the site doesn't recognize her.  And these are just the folks who are contacting us.  We don't know how many others have tried and were unable to access the site.

We are frustrated and disappointed that this is happening.  It really affects the trust level for people and that can be hard to overcome.

What is happening?  How can these issues get resolved as quickly as possible?

Other more minor stuff:  a number of people are having trouble finding the change password area.  It needs to be more prominent.  And a number of people don't know what Avatar is or means and how to upload their pictures.  Needs to be more explicit--especially for less digitally literate folks.  A sentence of instruction perhaps.

Lets talk soon,
Wendy

**Comment by wideopenspaces** [comment]
I've broken the issues into separate tickets so closing this one
