### ISSUE TITLE
Slowdowns on site

### ISSUE THREAD

**Issue by thoughtlead** [thoughtlead/ThoughtLead#24]
From Engine Yard,

Your site is experiencing a few swap issues when your indexer is running. You are running a full index quite often and that process takes upwards of 250MB which is causing your slice to swap. When this happens your mongrels are slowing down pretty substantially. I would consider adding more memory to your servers in the long term in addition to lessening your indexing frequency.

Thanks.

**Comment by wideopenspaces** [comment]
Reposted to the existing bug for site speed. Please post future info related to site speed there. Thanks! Closing this as a duplicate
