### ISSUE TITLE
Export users needs to reflect access levels

### ISSUE THREAD

**Issue by thoughtlead** [thoughtlead/ThoughtLead#25]
It's still just for Registered and Premium.

**Comment by wideopenspaces** [comment]
Quick question here - "Premium" includes all paid users. Do we want to start exporting the user's access level name as part of the exported file? That's what I'm going to do

**Comment by wideopenspaces** [comment]
Oops, sorry, I just relooked at my fix here and realized that's not true. Premium is only including "Premium" members. Fixing that.

**Comment by wideopenspaces** [comment]
Done. Can be checked out on staging shortly
