### ISSUE TITLE
Timestamps in forum don't reflect reality

### ISSUE THREAD

**Issue by thoughtlead** [thoughtlead/ThoughtLead#30]

**Comment by wideopenspaces** [comment]
fixed. deploy 12/14

**Comment by thoughtlead** [comment]
can you tell me what changes will affect sites and what is still there. In other words, there are some discussions on nourishingdestiny.com where entire strings say "4 hours ago" even though they happened within the last week. Was the change just to future time stamps, or is there a way to affect all previous ones?

**Comment by wideopenspaces** [comment]
timestamps were accurate in the database, but for some reason the code previously written to handle its display stopped working reliably. I have changed the code to use Rails' built-in 'time_ago_in_words' feature, which will affect display of all timestamps on responses.

Try checking out the 'Time is not Updated' thread. It was previously giving incorrect dates, but is now working as expected.
