### ISSUE TITLE
Extra "upgrade" buttons

### ISSUE THREAD

**Issue by thoughtlead** [thoughtlead/ThoughtLead#33]
I want to put extra buttons on the upsell page for people to upgrade before they get to the bottom. Simply pasting the code from the bottom button doesn't work, as there appears to be an authenticity token required for the button to work. Is there a simple fix for this one or is it more involved?

**Comment by wideopenspaces** [comment]
I removed the authenticity token requirement - you should be able to copy/paste the buttons now.
