### ISSUE TITLE
Disable access class "Free membership" on nourishingdestiny.com

### ISSUE THREAD

**Issue by thoughtlead** [thoughtlead/ThoughtLead#4]
Lonny created it before realizing that "Registered" membership appears on the checkout page already. Now when he tries to delete it, he just gets a "We're sorry but something went wrong" error.

**Comment by thoughtlead** [comment]
from Lonny: When you look at the list of access levels you'll see that two boxes are collapsed on each other. THis may have to do with why I can delete other access levels.

**Comment by wideopenspaces** [comment]
Gone!
