### ISSUE TITLE
Recurring billing issues

### ISSUE THREAD

**Issue by thoughtlead** [thoughtlead/ThoughtLead#50]
---------- Forwarded message ----------
From: Joanne Allgoewer joallgo@gmail.com
Date: Sun, Jan 24, 2010 at 1:57 PM
Subject: Technical questions
To: Diane Bardwell dianebardwell@gmail.com

Hi Dianne:

I was just looking at my profile on the site and it was showing that I needed to make another payment.  I set that up, and it went through, congratulating me yet again for becoming a premium member (which I'd already done in December).  Now I'm concerned on two fronts.  First, I think I put the wrong expiry date on my Mastercard when I entered it today.  Perhaps the system caught that, because now my profile is back to saying next payment due 2010/01/01.  But I'm worried I'm now going to be double billed if I re-enter the information now.   I'd somehow assumed you'd automatically take the monthly payments from my card when I first signed on (December 1st), though I've just checked my credit card statement on line and I don't see a payment in January.  Is this intended to be a month to month payment system?  (If so, that's fine, I'll just need to remember to keep doing it).

Can you forward the correct info to whoever administers payments, or confirm that I should just start the process again?

Joanne Allgoewer
Credit card ending in ***5190
Correct expiry date should be 08/10.

Thanks!

Joanne

**Comment by wideopenspaces** [comment]
Recurring bill issues should be cleared up now, everyone who wasn't rebilled between 9/1/09 and now is currently set to rebill on the 3rd of each month. Most people got some free months in between, as the current charges reflect payment for 2/3/10 to 3/3/10 - may want to communicate with site owners to find out what they want to do with interim charges.
