### ISSUE TITLE
Recurring revenue

### ISSUE THREAD

**Issue by thoughtlead** [thoughtlead/ThoughtLead#7]
The site (eatingforevolution.com) is not charging monthly fees to monthly members. They need to be charged.

Will the change cause people to be charged for past use? How far back?

**Comment by thoughtlead** [comment]
I just learned that the Automated Recurring Billing feature wasn't activated on Tiffany's Authorize.net account. She just turned it on. Is there anything we need to do to make the platform's recurring billing work?

**Comment by wideopenspaces** [comment]
Hm, not sure. I think that it should start working on the next cycle, but I will check that out.

**Comment by wideopenspaces** [comment]
Haven't heard any news here, so assuming the rebilling is now working as expected. Reopen if there's an issue!
